import { SAMPLE_RECORDS, due, makeCsv, type Capture } from '../../src/core';
import { clearVault, readVault, replaceRecords, reviewCapture } from '../../src/storage';
import './style.css';

const app = document.querySelector<HTMLDivElement>('#app')!;
const isDemo = () => location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
const ns = () => isDemo() ? 'demo:' : '';
const route = () => location.pathname.replace(/\/$/, '') || '/';
const html = String.raw;
const esc = (value: string) => value.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
const setTitle = (title: string) => { document.title = title; };
const download = (records: Capture[]) => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([makeCsv(records)], { type: 'text/csv;charset=utf-8' })); a.download = 'keep-the-sentence.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 500); };

function header() { return html`<header class="site-header"><a class="wordmark" href="/" data-route><span aria-hidden="true">///</span> Keep the Sentence</a><nav aria-label="Main navigation"><a href="/demo" data-route>Demo</a><a href="#how">How it works</a><a href="/privacy" data-route>Privacy</a></nav></header>`; }
function footer() { return html`<footer><p>Save source sentences. Review them later.</p><p><a href="/privacy" data-route>Privacy</a> · <a href="/terms" data-route>Terms</a> · Built by Param Factory · v1.0.0</p><p class="generated-note">Illustration generated for this product.</p></footer>`; }
function demoBanner() { return html`<aside class="demo-banner" aria-label="Demo controls"><span><strong>Demo</strong> — sample data, nothing is saved</span><button id="reset-demo">Reset demo</button><a href="/" data-route data-exit-demo>Start for real</a></aside>`; }
function card(record: Capture, compact = false) { return html`<article class="phrase-card ${compact ? 'compact' : ''}"><span class="card-mark" aria-hidden="true"></span><p class="phrase">${esc(record.phrase)}</p><blockquote>${esc(record.context)}</blockquote><p class="gloss"><strong>Your meaning:</strong> ${esc(record.gloss)}</p><p class="source"><a href="${esc(record.url)}" target="_blank" rel="noreferrer">${esc(record.title)} <span class="external">(opens source)</span></a> · ${esc(record.language)}</p></article>`; }

async function productBoard(demo: boolean) {
  const vault = await readVault(demo ? 'demo:' : ''); const records = vault.records; const today = due(records)[0];
  return html`<section class="board" aria-labelledby="board-title"><div class="board-heading"><div><p class="eyebrow">${demo ? 'Sample review queue' : 'Your review queue'}</p><h2 id="board-title">${today ? 'Read the sentence first.' : 'Nothing due today.'}</h2></div><button class="quiet-button" id="export-csv" ${records.length ? '' : 'disabled'}>Export CSV</button></div>${today ? `<div class="review-row"><div>${card(today)}</div><div class="review-action"><p>Can you recall what <strong>${esc(today.phrase)}</strong> means here?</p><details><summary>Show your meaning</summary><p>${esc(today.gloss)}</p></details><button class="primary" id="remembered">I remembered it</button><p class="small">This marks one review today.</p></div></div>` : `<div class="empty"><p>Saved phrases will appear here after you capture one.</p><a class="primary link-button" href="/demo" data-route>Try sample phrases</a></div>`}<div class="saved-head"><h3>Saved phrases</h3><span>${records.length} total</span></div><div class="saved-list">${records.slice(0, 4).map((r) => card(r, true)).join('') || '<p>No saved phrases yet.</p>'}</div></section>`;
}
async function landing() {
  setTitle('Keep the Sentence — save words in context');
  app.innerHTML = html`${header()}<main id="main" tabindex="-1"><section class="hero"><div class="hero-copy"><p class="eyebrow">A local browser extension</p><h1>Save words with their sentence.</h1><p class="lede">For learners reading real pages who need a meaning without losing their place.</p><div class="actions"><a class="primary link-button" href="/demo" data-route>Try it with sample data</a><span>See a review queue right away.</span></div><ul class="facts"><li>Stays on your device</li><li>Works without an account</li><li>One-time download, no subscription</li></ul></div><figure class="hero-art"><img src="/assets/dithered-reading-margin.webp" width="1200" height="800" fetchpriority="high" decoding="async" alt="A blank open book, a bookmark, a flashcard, and halftone dots show a sentence becoming a review cue."></figure></section><section class="preview-section"><div class="section-label"><p class="eyebrow">A sentence stays attached</p><h2>Review the word where you met it.</h2></div>${await productBoard(false)}</section><section id="how" class="how"><p class="eyebrow">How it works</p><h2>Keep reading. Keep the source.</h2><ol><li><strong>Select the phrase.</strong><span>Choose “Keep this sentence” from the page menu.</span></li><li><strong>Write a short meaning.</strong><span>The capture card keeps the nearby sentences and source link.</span></li><li><strong>Review today’s queue.</strong><span>Try the phrase in context before you reveal your cue.</span></li></ol></section><section class="privacy-blurb"><div><p class="eyebrow">What it does not do</p><h2>It does not translate pages or collect a reading history.</h2></div><p>It saves only the phrase, nearby text, source link, and meaning you choose. Export your records as a CSV for Anki or your own archive.</p></section><section class="install"><div><p class="eyebrow">Install the extension</p><h2>Capture from any page you can read.</h2><p>Download the signed extension package. Your browser will ask you to load it as an unpacked extension during this first release.</p></div><a class="primary link-button" href="/downloads/keep-the-sentence-extension.zip" download>Download extension ZIP</a></section></main>${footer()}`;
}
async function demo() {
  setTitle('Demo — Keep the Sentence');
  const current = await readVault('demo:'); if (!current.records.length) await replaceRecords(SAMPLE_RECORDS, 'demo:');
  app.innerHTML = html`${header()}${demoBanner()}<main id="main" tabindex="-1"><section class="demo-intro"><p class="eyebrow">Try the real review flow</p><h1>Review a saved phrase in context.</h1><p class="lede">These phrases are sample data. Reset them whenever you want.</p></section>${await productBoard(true)}<section class="demo-capture"><p class="eyebrow">What capture keeps</p><h2>A phrase, two nearby sentences, source, and your cue.</h2><p>In the extension, select text on a page. Choose “Keep this sentence.”</p></section></main>${footer()}`;
}
function legal(kind: 'privacy' | 'terms') { const privacy = kind === 'privacy'; setTitle(`${privacy ? 'Privacy' : 'Terms'} — Keep the Sentence`); app.innerHTML = html`${header()}<main id="main" class="legal" tabindex="-1"><h1>${privacy ? 'Your reading notes stay on your device.' : 'Terms for Keep the Sentence.'}</h1>${privacy ? `<p>Keep the Sentence stores only the phrases and details you save. It uses your browser’s local extension storage. Records are encrypted with AES-GCM before storage.</p><p>The extension does not send your captures, source pages, or meanings to our servers. It has no analytics. The optional sample demo uses a separate local storage area and is discarded when you leave it.</p><p>You can export your phrases as CSV. Removing the extension or clearing its browser storage may remove your local data.</p>` : `<p>Keep the Sentence is a local reading utility. Use it only for text you may read and save for personal study.</p><p>Do not use the extension to redistribute source text. You are responsible for the web pages you select from.</p><p>The extension is provided as-is. It does not provide translation, learning advice, or a backup service.</p>`}<p><a href="/" data-route>Return home</a></p></main>${footer()}`; }
function notFound() { setTitle('Page not found — Keep the Sentence'); app.innerHTML = html`${header()}<main id="main" class="not-found" tabindex="-1"><h1>This page is not in the notebook.</h1><p>Try the home page or the sample review queue.</p><p><a class="primary link-button" href="/" data-route>Go home</a></p></main>${footer()}`; }
async function render() { const path = route(); if (path === '/') await landing(); else if (path === '/demo') await demo(); else if (path === '/privacy' || path === '/terms') legal(path.slice(1) as 'privacy' | 'terms'); else notFound(); bind(); document.querySelector<HTMLElement>('h1')?.focus(); }
function bind() {
  document.querySelectorAll<HTMLAnchorElement>('[data-route]').forEach((a) => a.addEventListener('click', async (e) => { e.preventDefault(); if (a.hasAttribute('data-exit-demo')) await clearVault('demo:'); history.pushState({}, '', a.href); render(); }));
  document.querySelector('#reset-demo')?.addEventListener('click', async () => { await replaceRecords(SAMPLE_RECORDS, 'demo:'); await render(); });
  document.querySelector('#remembered')?.addEventListener('click', async () => { const record = due((await readVault(ns())).records)[0]; if (record) { await reviewCapture(record.id, ns()); await render(); } });
  document.querySelector('#export-csv')?.addEventListener('click', async () => download((await readVault(ns())).records));
}
window.addEventListener('popstate', render); render().catch(() => { app.innerHTML = '<main id="main"><h1>Your local notes could not load.</h1><p>Reload this page. If it still fails, reset the demo and try again.</p></main>'; });
